- CHANGELOG.md
- vendor/github.com/gliderlabs/ssh/session.go
Fix #22 
*Temporary fix*
A better solution requires a refactor of the ssh session handler (related with #24)
Related with this comment: https://github.com/gliderlabs/ssh/issues/47#issuecomment-340550104
> Fix connection failure when sending too many environment variables

- CHANGELOG.md
- dbinit.go
The default created user now has the same username as the user starting sshportal (was hardcoded admin)
> Dynamic username for the first created account

- db.go
- dbinit.go
- pkg/bastionsession/bastionsession.go
- shell.go
- ssh.go
This PR allows admins to define a "hop" when creating a server (typically needed when a machine is inside a walled network, with only one entrypoint).
The feature is implemented as follows:
- when creating a host, there is a possiblity to add a "hop"
- hops are referend them with the name of the host in sshportal
- the hop ID is then saved in the DB in the hosts table
- when connecting to a host, sshportal will recurse through all the possible hops of a host (allowing chained proxies)
I don’t know if this feature is wanted, but we found it quite useful. I couldn't find a contributing guide, but I'm of course open to any code change that may be needed to properly integrate this code in the project.
> Implement proxied connections

- shell.go
This PR shows 'n/a' in the appropriate field in cases of missing user or host when doing a `session ls` or `userkey ls`, thus avoiding a crash if listing sessions or userkeys after removing the host or user they reference.
**Which issue this PR fixes**: fixes #53 (`userkey ls` crashes) and also some `session ls` crashes.
Not sure this is the right way to fix this. Maybe userkeys should juste be removed alongside the associated user as there doesn't seem to be a point to keeping them around ? Also maybe database constraints should be added to avoid breaking relations ? Don't hesitate to tell me and I will look into modifying the PR accordingly.
> Show 'n/a' in case of missing information to avoid crashing.

- pkg/bastionsession/bastionsession.go
- vendor/github.com/arkan/bastion/pkg/logchannel/logchannel.go
Add log for exec request.
This deals with session opened with:
ssh bastion -l host1 "rm -rf > /dev/null 2>&1 " which was not audited.
This PR depends on https://github.com/arkan/bastion/pull/4.
> Add log for exec request.

- shell.go
- ssh.go
**Which issue this PR fixes**
* Commit [`251ab85`](https://github.com/vdaviot/sshportal/commit/251ab85702f324e49b6f57fcf7219ea9b338d9bb) fixes:
* [`#71`](https://github.com/moul/sshportal/issues/71): session ls fails with "Error 1390: Prepared statement contains too many placeholders"
* Also contains fixes for: [`#72`](https://github.com/moul/sshportal/issues/72) and [`#62`](https://github.com/moul/sshportal/issues/62) ([`1695d4f`](https://github.com/vdaviot/sshportal/commit/1695d4f0b8ae388816abc6d71851a1730fe661fe)) as they are mandatory to test.
**What this PR does / why we need it**
If the mySQL database held too many records, the ``session ls`` command failed with an error message. The hard limit of records by query in mySQL is  65,535.
It now queries by batch of 60000 to solve the …
> [FIX] Session ls on big databases 

- shell.go
**Which issue this PR fixes**
* Commit [`101b363`](https://github.com/vdaviot/sshportal/commit/101b363eea3063c70d73d854f3a173ffab4a1fee) fixes:
* [`#70`](https://github.com/moul/sshportal/issues/70): Unsetting a hop from a host unsets the hops from all the hosts it is set on
**What this PR does / why we need it**
The command ``host update --unset-hop <host>`` removed the host's hop from every hosts and not only the given one.
It now remove the hop only on the given host.
> [FIX] unsetting hop on host

- ssh.go
**Which issue this PR fixes**
* Commit [`1695d4f`](https://github.com/vdaviot/sshportal/commit/1695d4f0b8ae388816abc6d71851a1730fe661fe) fixes:
* [`#72`](https://github.com/moul/sshportal/issues/72): Sessions status were displayed as if they were closed even if active.
* [`#62`](https://github.com/moul/sshportal/issues/62): Sessions durations were therefore not correct.
**What this PR does / why we need it**
Sessions status and duration are displayed properly.
> [FIX] session status and duration displaying properly

- db.go
- shell.go
`echo "ssh-rsa key ..." | ssh localhost -p 2222 -l admin userkey create` shawn
Without the PR, it shows `error: Key: non zero value required;AuthorizedKey: non zero value required;`
For the AuthorizedKey, I compared the code in ssh.go, I thought it might be missing.
For the Key, it is a []byte field. The required valid cause Key: non zero value required.
**Which issue this PR fixes**: fixes #xxx, fixes #xxx...
fixes #46 
```diff
--- a/db.go
+++ b/db.go
@@ -70,7 +70,7 @@ type Host struct {
// UserKey defines a user public key used by sshportal to identify the user
type UserKey struct {
gorm.Model
-       Key           []byte `sql:"size:10000" valid:"required,length(1|10000)"`
+       Key           []byte …
```
> Fix userkey create.

- pkg/bastion/session.go
- pkg/bastion/ssh.go
Hi @moul 
This PR fixes a little problem on the display of newly created bastion session:
`Jan 23 09:21:09 foosshportal1 c00617c0c9aa[1422]: 2019/01/23 08:21:09 New connection(bastion): sshUser="barfaz" remote="172.17.0.1:58570" local="172.17.0.3:2222" dbUser=id:'#',email:blabla@foobar.fr`
Here `dbUser` appears as the # character from ASCII table, as his id is 35.
I changed the format from %q to %d to fix the problem.
Another things that is included is this commit is the fix discussed by @kreanda in [#56](https://github.com/moul/sshportal/issues/56)
It was annoying to multiple people in the company and is imo a QOL improvement.
Do not hesitate to tell me if there's another way to do it :)
Thanks again for the great tool :) :100:
> [FIX] Format of id in new session | Closing channel if host unreachable

- pkg/bastion/ssh.go
This PR fixes a issue with encrypted sshkeys. If you are using AES encryption, you are not able to connect to hosts.
Error you are received:
error: ssh: no key found
Connection to sshportal closed.
> [fix] unable to use encrypted ssh private keys

- pkg/bastion/session.go
- pkg/bastion/ssh.go
This PR adds username and session ID to the tty session log filename. This makes it easier/quicker to find the person and session associated with it without having to look at sshportal logs or comparing dates in `session ls` output.
> Add username and session ID to session log filename.

- pkg/bastion/shell.go
- pkg/dbmodels/dbmodels.go
This PR allows to create a host using an ip address as its name. This is sometimes useful when a host has no dns name and they're is no obvious way to name it other than by its address.
The PR does two things:
* remove the unix_user constraint on host names in dbmodels.go as it forbids to have a name starting with a number.
* add a check using a regex in shell.go to detect when the name is an ip (v4 only) and avoid splitting on "." in that case as that would make no sense.
> Allow to create a host using an ip as name

- pkg/bastion/session.go
This PR just changes the mode on created tty log files. It seems to me it makes sense to have them set as read-only since they are audit files that usually have no reason to be altered outside of sshportal. This can help prevent mistakes (such as overwriting a log file by mistakenly using ttyrec on it instead of ttyplay, which happened to me).
> Set log files mode to 440 instead of 640.

- _config.yml
- go.mod
- go.sum
- helm/sshportal/.helmignore
- helm/sshportal/Chart.yaml
- helm/sshportal/templates/NOTES.txt
- helm/sshportal/templates/_helpers.tpl
- helm/sshportal/templates/deployment.yaml
- helm/sshportal/templates/horizontal-pod-autoscaling.yaml
- helm/sshportal/templates/service.yaml
- helm/sshportal/templates/tests/test-connection.yaml
- helm/sshportal/values.yaml
Add Helm chart to deploy SSHPortal on Kubernetes.
The chart support HA and standalone configuration.
**Which issue this PR fixes**:
N/A
> Add Helm chart to deploy SSHPortal on Kubernetes

- pkg/bastion/ssh.go
A very minor (1 char) fix for log lines written when connecting to the admin shell. Currently the `dbUser=id:` is not interpreted as an int, resulting in weird characters showing up instead of the user id. (this is the same problem that was already fixed some time ago line 93)
> Fix db user id type in shell connection log.

- examples/integration/_client.sh
It's just a little correction: hostgroup instead of usergroup, because it should be hostgroup, especially because hg1 and hg2 are hostgroups
> Little correction

- README.md
Ran into issues where i tried to share a personal host named as the user who tried to access it.
**Which issue this PR fixes**: fixes #xxx, fixes #xxx...
Update the readme to correspond to the behavior defined by https://github.com/moul/sshportal/blob/v1.12.2/pkg/bastion/ssh.go#L50-L53
Maybe consider only dropping into a shell if the email is provided, not the username.
> Update readme; special host names

- README.md
**What this PR does / why we need it:**
Current readme does not inform user of how to fix the behaviour of password promt when linking admin account
**Which issue this PR fixes: fixes #128**
Updated the readme to inform the user of a quick fix (ssh-keygen -t rsa) when association fails and user is asked for password
> Update README.md; Info about missing host keys

- pkg/bastion/session.go
- pkg/bastion/ssh.go
In the current implementation, usage of an inline shell command through SSH is broken (see #55 and #127).
This bug prevents usage of sshportal with CI and automation tools (jenkins, ansible etc...).
This issue is due to some race conditions in the go subroutines leading to:
* early quit because a SSH_MSG_CHANNNEL_CLOSE packet was processed by the main function but EOF wasn't read yet by the subroutine in the data stream
* early quit because the subroutine reading the data stream reached EOF but the main function didn't process yet the last packets in the requests channel (SSH_MSG_CHANNEL_REQUEST/exit-status and SSH_MSG_CHANNNEL_CLOSE)
Because of this race condition, the following can happen:
* Output of the inline shell command isn't copied from rch …
> Fix early closure of data stream.

- pkg/dbmodels/dbmodels.go
We use format "username:hostname" as hostname for some of our servers. In sometimes we get error:
```
error: Name: server.name:sergey.yashchuk does not validate as length(1|32)
```
As I can see in database fields have length 255 symbols already (not sure how's it in MySQL):
```
SQLite version 3.22.0 2018-01-22 18:45:57
Enter ".help" for usage hints.
sqlite> .tables
acls              hosts             user_group_acls   user_user_roles
events            migrations        user_groups       users
host_group_acls   sessions          user_keys
host_groups       settings          user_roles
host_host_groups  ssh_keys          user_user_groups
sqlite> .schema hosts
CREATE TABLE IF NOT EXISTS "hosts" ("id" integer primary key autoincrement,"created_at" datetime,"updated_at" datetime,"deleted_at" …
```
> fix: increase size of name fields

- pkg/bastion/shell.go
If the invite leaks for the admin user it is possible for the admin
user to be compromised by another invite request.  It needs to be
possible to entirely remove the invite capability for any given user.
New arguments added to user update:
```
--invite_token value, -i value            Updates the invite token
--remove_invite, -R                       Remove invite token
```
Signed-off-by: Jason Wessel <jason.wessel@windriver.com>
> feat: Allow for update or removal of the invite token

- pkg/bastion/shell.go
- pkg/dbmodels/dbmodels.go
The userkey rm command implies that it can remove a key by user or the
id key, but it only works against the data base id of the key.  This
patch allows the userkey rm command to work with the user name, so
that all the keys for the user can be cleared out in one command.
Signed-off-by: Jason Wessel <jason.wessel@windriver.com>
> feat: Allow removal by user for 'userkey rm'

- pkg/dbmodels/dbmodels.go
Postgres is more picky about submitting a string to the id column in a
table.  Postgres requires the use of only integers for the array of
values in a select statement containing: where id IN (...array...)
This patch fixes all the following class of problems:
```sql
SELECT * FROM "ssh_keys" WHERE
"ssh_keys"."deleted_at" IS NULL AND ((id IN ('host')) OR (name IN
('host'))) ORDER BY "ssh_keys"."id" ASC LIMIT 1 [0 rows affected or
returned ] error: pq: invalid input syntax for
type integer: "host"
```
Signed-off-by: Jason Wessel <jason.wessel@windriver.com>
> feat: Add postgres support

- pkg/bastion/shell.go
The most simple case with a fresh install of sshportal using the
following commands put the shell into a unrecoverable state.
```console
config> host create test1@test1
1
config> host inspect 1
config> host create test2@test2
error: can't preload field Groups for dbmodels.SSHKey
```
The issue is caused because the global db handle is replaced with the
inspect command.
> fix: host inspect causes db errors with later operations
